server:
  port: 8082

spring:
  application:
    name: EMPLOYEE-SERVICE # Gateway isi naam ko dhoondega
  datasource:
    url: jdbc:mysql://localhost:3306/employee_DB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# Eureka settings (Standard Spring Boot structure)
eureka:
  instance:
    prefer-ip-address: true # DNS issue resolve karne ke liye
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/